name: Production Grade Workflow

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  system-check-job:
    name: System Health Check
    runs-on: ubuntu-latest
    
    timeout-minutes: 10

    steps:
      - name: Print System Info
        run: |
          echo "Starting the advanced workflow..."
          echo "Current Date: $(date)"
          echo "Running on Node Version: $(node -v)"
      
      - name: Say Goodbye
        run: echo "Job Completed Successfully!"
