name: Production Grade Workflow

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  system-check-job:
    name: System Health Check
    runs-on: ubuntu-latest
    
    timeout-minutes: 10

    steps:
      - name: Print System Info
        run: |
          echo "Starting the advanced workflow..."
          echo "Current Date: $(date)"
          echo "Running on Node Version: $(node -v)"
      
      - name: Say Goodbye
        run: echo "Job Completed Successfully!"
      
      - name: Multi-line Logic Test
        run: |
                echo "Testing memory persistence..."
                export USER_ROLE="Admin"
                echo "User is: $USER_ROLE"
                
                echo "Testing error handling..."
                ls /fake-folder || echo "Folder not found, but continuing..."
                echo "I am still alive!"
